vim.o.guicursor = "a:block"
vim.o.relativenumber = true
vim.o.nu = true
vim.o.nohlsearch = true
vim.o.hidden = true
vim.o.noerrorbells = true
vim.o.tabstop=4 
vim.o.softtabstop=4
vim.o.shiftwidth=4
vim.o.expandtab = true
vim.o.smartindent = true
vim.o.nowrap = true
vim.o.noswapfile = true
vim.o.nobackup = true
vim.o.undodir = "~/.vim/undodir"
vim.o.undofile = true
vim.o.incsearch = true
vim.o.termguicolors = true
vim.o.scrolloff = 8
vim.o.noshowmode = true
vim.o.clipboard = "unnamedplus"
vim.o.ignorecase = true
vim.o.autoindent = true
vim.o.smartcase = true
