add_newline = false

[username]
show_always = true
format = "[$user](bold #ff5370) in "

[directory]
truncate_to_repo = false
style = "bold #c792ea"

[git_branch]
style = "bold #89ddff"

[git_status]
disabled = true
style = "bold #ff5370"

[cmd_duration]
disabled = true

[nodejs]
style = "bold #09f7a0"

[character]
success_symbol = "[❯](bold #9ccfd8)" 
error_symbol = "[❯](bold 203)"

