add_newline = false

[username]
show_always = true
format = "[$user](#d59192) in "

[directory]
truncate_to_repo = false
style = "#b99be5"

[git_branch]
style = "#a8a1be"

[git_status]
disabled = true
style = "#eb6f92"

[package]
style = "#cbaa88"

[cmd_duration]
disabled = true

[nodejs]
style = "#939374"

[docker_context]
disabled = true

[character]
success_symbol = "[❯](#9ccfd8)" 
error_symbol = "[❯](203)"

