add_newline = false

[username]
show_always = true
format = "[$user](bold #ff7b72) in "

[directory]
truncate_to_repo = false
style = "bold #d2a8ff"

[git_branch]
style = "bold #79c0ff"

[git_status]
disabled = true
style = "bold #f85149"

[cmd_duration]
disabled = true

[nodejs]
style = "bold #a9ff68"

[character]
success_symbol = "[❯](bold #9ccfd8)" 
error_symbol = "[❯](bold 203)"

