add_newline = false

[username]
show_always = true
format = "[$user](#31748f) in "

[directory]
truncate_to_repo = false
style = "#c4a7e7"

[git_branch]
style = "#ebbcba"

[git_status]
disabled = true
style = "#eb6f92"

[package]
style = "#f6c177"

[cmd_duration]
disabled = true

[nodejs]
style = "#9ccfd8"

[docker_context]
disabled = true

[character]
success_symbol = "[❯](#9ccfd8)" 
error_symbol = "[❯](203)"

