add_newline = false

[package]
disabled=true

[username]
show_always = true
format = "[$user](bold 167) in "

[directory]
truncate_to_repo = false
style = "bold 109"

[git_branch]
style = "bold 175"

[git_status]
style = "bold 108"

[cmd_duration]
disabled = true

[nodejs]
style = "bold 142"

