add_newline = false

[package]
disabled=true

[username]
show_always = true
format = "[$user](bold #eb6f92) in "

[directory]
truncate_to_repo = false
style = "bold #f6c177"

[git_branch]
style = "bold #9ccfd8"

[git_status]
style = "bold #eb6f92"

[cmd_duration]
disabled = true

[nodejs]
style = "bold #c4a7e7"

