add_newline = false

[username]
show_always = true
format = "[$user](bold #bb9af7) in "

[directory]
truncate_to_repo = false
style = "bold #ff9e64"

[git_branch]
style = "bold #73daca"

[git_status]
style = "bold #db4b4b"

[cmd_duration]
disabled = true

[nodejs]
style = "bold #1abc9c"

[character]
success_symbol = "[❯](bold #9ccfd8)" 
error_symbol = "[❯](bold 203)"

