add_newline = false

[username]
show_always = true
format = "[$user](#bf616a) in "

[directory]
truncate_to_repo = false
style = "#d08770"

[git_branch]
style = "#88c0d0"

[git_status]
disabled = true
style = "#eb6f92"

[package]
style = "#ebcb8b"

[cmd_duration]
disabled = true

[nodejs]
style = "#a3be8c"

[docker_context]
disabled = true

[character]
success_symbol = "[❯](#9ccfd8)" 
error_symbol = "[❯](203)"

