vim.api.nvim_create_user_command("Authorize", function(opts)
	vim.cmd([[%s/\(prototype.* =\) \(async.*\)/\1{\rauthorize: ["]] .. opts.fargs[1] .. [["],\rrule: \2]])
	vim.cmd("norm GI}")
	vim.cmd("w")
end, { nargs = 1 })
