vim.api.nvim_create_user_command("CleanService", function()
	vim.cmd([[%s/.*.prototype.\(.*\) = {.*\n.*\n.*rule: \(.*\)/exports.\1 = \2/ge]])
	vim.cmd([[%s/.*.prototype.\(.*\) = \(.*\)/exports.\1 = \2/ge]])
	vim.cmd([[%s/},\n};/};/ge]])
	vim.cmd("w")
end, {})

vim.api.nvim_create_user_command("CleanServices", function()
	vim.cmd([[bufdo %s/.*.prototype.\(.*\) = {.*\n.*\n.*rule: \(.*\)/exports.\1 = \2/ge]])
	vim.cmd([[bufdo %s/.*.prototype.\(.*\) = \(.*\)/const \1 = \2/ge]])
	vim.cmd([[bufdo %s/},\n};/};/ge]])
	vim.cmd([[bufdo %s/const import\./const /ge]])
	vim.cmd([[bufdo %s/this\.reference\.//ge]])
	vim.cmd("w")
end, {})
