add_newline = false

[username]
show_always = true
format = "[$user](#c4746e) in "

[directory]
truncate_to_repo = false
style = "#b98d7b"

[git_branch]
style = "#8ba4b0"

[git_status]
disabled = true
style = "#c4746e"

[package]
style = "#b6927b"

[cmd_duration]
disabled = true

[nodejs]
style = "#7a8a6c"

[docker_context]
disabled = true

[character]
success_symbol = "[λ](#7a8a6c)" 
error_symbol = "[λ](#8ba4b0)"

