add_newline = false

[username]
show_always = true
format = "[$user](#65b1cd) in "

[directory]
truncate_to_repo = false
style = "#ccb1ed"

[git_branch]
style = "#f0a4a2"

[git_status]
disabled = true
style = "#eb6f92"

[package]
style = "#f6c177"

[cmd_duration]
disabled = true

[nodejs]
style = "#a3be8c"

[docker_context]
disabled = true

[character]
success_symbol = "[❯](#a3be8c)" 
error_symbol = "[❯](203)"

