add_newline = false

[username]
show_always = true
format = "[$user](#491acc) in "

[directory]
truncate_to_repo = false
style = "#2e4f85"

[git_branch]
style = "#067a82"

[git_status]
disabled = true
style = "#ff5370"

[package]
style = "#a43a14"

[cmd_duration]
disabled = true

[nodejs]
style = "#c3e88d"

[docker_context]
disabled = true

[character]
success_symbol = "[λ](#ffcb6b)" 
error_symbol = "[λ](#ff5370)"
