add_newline = false

[username]
show_always = true
format = "[$user](#61afef) in "

[directory]
truncate_to_repo = false
style = "#c678dd"

[git_branch]
style = "#56b6c2"

[git_status]
disabled = true
style = "#e06b75"

[package]
style = "#d19a66"

[cmd_duration]
disabled = true

[nodejs]
style = "#98c379"

[docker_context]
disabled = true

[character]
success_symbol = "[λ](#56b6c2)"
error_symbol = "[λ](#e06b75)"
